server:
  port: 9000
spring:
  profiles:
    active: native
  application:
    name: config-server  # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/weijiangchao-linjiang/config #配置文件所在仓库
          username:
          password:
          default-label: master
          search-paths: config
          force-pull: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:13000/eureka,http://localhost:13001/eureka
  server:
    enable-self-preservation: false
  instance:
    #    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30