#server:
#  port: 11001
#spring:
#  application:
#    name: service-provider
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 42.193.131.33:8848
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:13000/eureka,http://localhost:13001/eureka
#  server:
#    enable-self-preservation: false
#  instance:
##    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 30
