server:
  port: 13001
spring:
  application:
    name: eurekaserver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:13000/eureka,http://localhost:13001/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
